<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup><LibusbRoot>$(HeadUnitRoot)third_party\libusb</LibusbRoot></PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile><AdditionalIncludeDirectories>$(LibusbRoot)\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories></ClCompile>
    <Link>
      <AdditionalLibraryDirectories>$(LibusbRoot)\x64;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>libusb-1.0.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
  <Target Name="DeployLibusb" AfterTargets="Build">
    <Copy SourceFiles="$(LibusbRoot)\x64\libusb-1.0.dll" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" />
  </Target>
</Project>
